package com.yamp.ui.screen.home

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.yamp.data.repository.PlaylistRepository
import com.yamp.data.repository.TrackRepository
import com.yamp.data.repository.UserPreferencesRepository
import com.yamp.domain.usecase.metadata.FetchMetadataUseCase
import com.yamp.domain.usecase.recommendation.GetRecommendedNextUseCase
import com.yamp.domain.usecase.scan.ScanDeviceUseCase
import com.yamp.ui.state.HomeUiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class HomeViewModel @Inject constructor(
    private val scanDeviceUseCase: ScanDeviceUseCase,
    private val trackRepository: TrackRepository,
    private val playlistRepository: PlaylistRepository,
    private val userPreferences: UserPreferencesRepository,
    private val fetchMetadataUseCase: FetchMetadataUseCase,
    private val getRecommendedNextUseCase: GetRecommendedNextUseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow(HomeUiState())
    val uiState: StateFlow<HomeUiState> = _uiState.asStateFlow()

    fun onPermissionGranted() {
        _uiState.update { it.copy(permissionGranted = true) }
        scanDevice()
    }

    fun onPermissionDenied() {
        _uiState.update { it.copy(error = "Storage permission is required to scan music") }
    }

    fun scanDevice() {
        viewModelScope.launch {
            _uiState.update { it.copy(isScanning = true, error = null) }
            try {
                val count = scanDeviceUseCase()
                _uiState.update { it.copy(isScanning = false, scanProgress = "$count tracks found") }
                if (userPreferences.autoFetchMetadata.first()) {
                    fetchMetadataUseCase { _, _ -> }
                }
                loadData()
            } catch (e: Exception) {
                _uiState.update { it.copy(isScanning = false, error = e.message) }
            }
        }
    }

    private fun loadData() {
        viewModelScope.launch {
            trackRepository.getAllTracks().collect { tracks ->
                _uiState.update { it.copy(recentTracks = tracks.take(20)) }
            }
        }
        viewModelScope.launch {
            playlistRepository.getAutoGeneratedPlaylists().collect { playlists ->
                _uiState.update { it.copy(folderPlaylists = playlists) }
            }
        }
        loadRecommendations()
    }

    fun loadRecommendations() {
        viewModelScope.launch {
            try {
                val recommendations = getRecommendedNextUseCase()
                _uiState.update { it.copy(recommendedNext = recommendations) }
            } catch (_: Exception) {
                // Silently fail - recommendations are optional
            }
        }
    }
}
