package com.yamp.data.repository

import com.yamp.domain.model.Playlist
import kotlinx.coroutines.flow.Flow

interface PlaylistRepository {
    fun getAllPlaylists(): Flow<List<Playlist>>
    fun getAutoGeneratedPlaylists(): Flow<List<Playlist>>
    suspend fun getPlaylistById(id: Long): Playlist?
    suspend fun createOrUpdateFolderPlaylist(folderPath: String, trackIds: List<Long>)
    suspend fun deletePlaylist(id: Long)
}
