package com.yamp.data.repository

import com.yamp.data.local.db.dao.PlaylistDao
import com.yamp.data.local.db.entity.PlaylistEntity
import com.yamp.data.local.db.entity.PlaylistTrackCrossRef
import com.yamp.data.mapper.toDomain
import com.yamp.domain.model.Playlist
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject

class PlaylistRepositoryImpl @Inject constructor(
    private val playlistDao: PlaylistDao
) : PlaylistRepository {

    override fun getAllPlaylists(): Flow<List<Playlist>> =
        playlistDao.getAllPlaylists().map { it.toDomain() }

    override fun getAutoGeneratedPlaylists(): Flow<List<Playlist>> =
        playlistDao.getAutoGeneratedPlaylists().map { it.toDomain() }

    override suspend fun getPlaylistById(id: Long): Playlist? =
        playlistDao.getPlaylistById(id)?.toDomain()

    override suspend fun createOrUpdateFolderPlaylist(folderPath: String, trackIds: List<Long>) {
        val folderName = folderPath.substringAfterLast('/')
        val now = System.currentTimeMillis()

        val existing = playlistDao.getPlaylistByFolderPath(folderPath)
        val playlistId = if (existing != null) {
            playlistDao.clearPlaylistTracks(existing.playlistId)
            existing.playlistId
        } else {
            playlistDao.insertPlaylist(
                PlaylistEntity(
                    name = folderName,
                    description = folderPath,
                    coverArtUri = null,
                    isAutoGenerated = true,
                    sourceFolderPath = folderPath,
                    createdAt = now,
                    updatedAt = now
                )
            )
        }

        val crossRefs = trackIds.mapIndexed { index, trackId ->
            PlaylistTrackCrossRef(
                playlistId = playlistId,
                trackId = trackId,
                sortOrder = index
            )
        }
        playlistDao.insertPlaylistTrackCrossRefs(crossRefs)
    }

    override suspend fun deletePlaylist(id: Long) =
        playlistDao.deletePlaylist(id)
}
