package com.yamp.data.mapper

import com.yamp.data.local.db.entity.PlaylistWithTracks
import com.yamp.domain.model.Playlist

fun PlaylistWithTracks.toDomain(): Playlist = Playlist(
    id = playlist.playlistId,
    name = playlist.name,
    description = playlist.description,
    coverArtUri = playlist.coverArtUri,
    isAutoGenerated = playlist.isAutoGenerated,
    tracks = tracks.toDomain(),
    trackCount = tracks.size
)

fun List<PlaylistWithTracks>.toDomain(): List<Playlist> = map { it.toDomain() }
