package com.yamp.data.mapper

import com.yamp.data.local.db.entity.PlaylistWithTracks
import com.yamp.domain.media.pickRepresentativeArtwork
import com.yamp.domain.model.Playlist

fun PlaylistWithTracks.toDomain(): Playlist {
    val domainTracks = tracks.toDomain()
    return Playlist(
        id = playlist.playlistId,
        name = playlist.name,
        description = playlist.description,
        coverArtUri = playlist.coverArtUri ?: pickRepresentativeArtwork(domainTracks),
        isAutoGenerated = playlist.isAutoGenerated,
        tracks = domainTracks,
        trackCount = domainTracks.size
    )
}

fun List<PlaylistWithTracks>.toDomain(): List<Playlist> = map { it.toDomain() }
