package com.yamp.data.local.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey(autoGenerate = true) val playlistId: Long = 0,
    val name: String,
    val description: String?,
    val coverArtUri: String?,
    val isAutoGenerated: Boolean,
    val sourceFolderPath: String?,
    val createdAt: Long,
    val updatedAt: Long
)
