package com.yamp.domain.model

data class Playlist(
    val id: Long,
    val name: String,
    val description: String?,
    val coverArtUri: String?,
    val isAutoGenerated: Boolean,
    val tracks: List<Track>,
    val trackCount: Int
)
