package com.yamp.data.local.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import com.yamp.data.local.db.entity.PlaylistEntity
import com.yamp.data.local.db.entity.PlaylistTrackCrossRef
import com.yamp.data.local.db.entity.PlaylistWithTracks
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaylistDao {

    @Transaction
    @Query("SELECT * FROM playlists ORDER BY name ASC")
    fun getAllPlaylists(): Flow<List<PlaylistWithTracks>>

    @Transaction
    @Query("SELECT * FROM playlists WHERE playlistId = :id")
    suspend fun getPlaylistById(id: Long): PlaylistWithTracks?

    @Transaction
    @Query("SELECT * FROM playlists WHERE isAutoGenerated = 1 ORDER BY name ASC")
    fun getAutoGeneratedPlaylists(): Flow<List<PlaylistWithTracks>>

    @Query("SELECT * FROM playlists WHERE sourceFolderPath = :folderPath LIMIT 1")
    suspend fun getPlaylistByFolderPath(folderPath: String): PlaylistEntity?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylist(playlist: PlaylistEntity): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylistTrackCrossRefs(crossRefs: List<PlaylistTrackCrossRef>)

    @Query("DELETE FROM playlist_track_cross_ref WHERE playlistId = :playlistId")
    suspend fun clearPlaylistTracks(playlistId: Long)

    @Query("DELETE FROM playlists WHERE playlistId = :id")
    suspend fun deletePlaylist(id: Long)
}
