package com.yamp.ui.screen.home

import com.google.common.truth.Truth.assertThat
import com.yamp.data.repository.PlaylistRepository
import com.yamp.data.repository.TrackRepository
import com.yamp.domain.model.Track
import com.yamp.domain.usecase.recommendation.GetRecommendedNextUseCase
import com.yamp.domain.usecase.scan.ScanDeviceUseCase
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class HomeViewModelTest {

    private lateinit var scanDeviceUseCase: ScanDeviceUseCase
    private lateinit var trackRepository: TrackRepository
    private lateinit var playlistRepository: PlaylistRepository
    private lateinit var getRecommendedNextUseCase: GetRecommendedNextUseCase
    private lateinit var viewModel: HomeViewModel
    private val testDispatcher = StandardTestDispatcher()

    @Before
    fun setup() {
        Dispatchers.setMain(testDispatcher)
        scanDeviceUseCase = mockk()
        trackRepository = mockk()
        playlistRepository = mockk()
        getRecommendedNextUseCase = mockk()

        coEvery { scanDeviceUseCase() } returns 10
        coEvery { trackRepository.getAllTracks() } returns flowOf(emptyList())
        coEvery { playlistRepository.getAutoGeneratedPlaylists() } returns flowOf(emptyList())
        coEvery { getRecommendedNextUseCase(any()) } returns emptyList()

        viewModel = HomeViewModel(
            scanDeviceUseCase, trackRepository, playlistRepository, getRecommendedNextUseCase
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    @Test
    fun `initial state has default values`() {
        val state = viewModel.uiState.value
        assertThat(state.isScanning).isFalse()
        assertThat(state.recentTracks).isEmpty()
        assertThat(state.recommendedNext).isEmpty()
        assertThat(state.error).isNull()
    }

    @Test
    fun `onPermissionDenied sets error`() {
        viewModel.onPermissionDenied()
        assertThat(viewModel.uiState.value.error).isNotNull()
    }

    @Test
    fun `onPermissionGranted triggers scan`() = runTest {
        viewModel.onPermissionGranted()
        advanceUntilIdle()
        assertThat(viewModel.uiState.value.permissionGranted).isTrue()
    }
}
