[Service]
Environment="JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64"
Environment="ANDROID_SDK_ROOT=/home/pranav/Android/Sdk"
Environment="ANDROID_HOME=/home/pranav/Android/Sdk"
Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/casc_configs"
Environment="JAVA_OPTS=-Djava.awt.headless=true -Dcasc.jenkins.config=/var/lib/jenkins/casc_configs"
Environment="PATH=/usr/lib/jvm/java-21-openjdk-amd64/bin:/home/pranav/Android/Sdk/platform-tools:/home/pranav/Android/Sdk/cmdline-tools/latest/bin:/home/pranav/Android/Sdk/build-tools/35.0.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
